language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

cache: bundler
bundler_args: --jobs=4 --retry=3

before_install: 'gem update --system'

script:
  - bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
