language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head

cache: bundler
bundler_args: --jobs=4 --retry=3

before_install: 'gem update --system'

script:
  - bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
